### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Aileensibs** [snugel/digenome-toolkit#1]
When I install this toolkit on my machine, error occurred with the bamtools, but I found the reported missing files by the error message are actually in the directory, so I can't figure out what's the problem here, could you please help me out?

Here is the error message:

1.find_position_bam.cpp:7:27: error: api/BamReader.h: No such file or directory
1.find_position_bam.cpp:10: error: ‘BamTools’ is not a namespace-name
1.find_position_bam.cpp:10: error: expected namespace-name before ‘;’ token
1.find_position_bam.cpp: In function ‘void usage()’:
1.find_position_bam.cpp:13: error: ‘cout’ was not declared in this scope
1.find_position_bam.cpp:13: error: ‘endl’ was not declared in this scope
1.find_position_bam.cpp:15: error: ‘exit’ was not declared in this scope
1.find_position_bam.cpp: In function ‘int main(int, char**)’:
1.find_position_bam.cpp:42: error: ‘BamReader’ was not declared in this scope
1.find_position_bam.cpp:42: error: expected ‘;’ before ‘reader’
1.find_position_bam.cpp:50: error: ‘reader’ was not declared in this scope
1.find_position_bam.cpp:53: error: expected type-specifier before ‘exception’
1.find_position_bam.cpp:53: error: expected ‘)’ before ‘&’ token
1.find_position_bam.cpp:53: error: expected ‘{’ before ‘&’ token
1.find_position_bam.cpp:53: error: ‘e’ was not declared in this scope
1.find_position_bam.cpp:53: error: expected ‘;’ before ‘)’ token
1.find_position_bam.cpp:62: error: ‘reader’ was not declared in this scope
1.find_position_bam.cpp:64: error: ‘SamHeader’ does not name a type
1.find_position_bam.cpp:65: error: ‘RefVector’ does not name a type
1.find_position_bam.cpp:67: error: ‘BamAlignment’ was not declared in this scope
1.find_position_bam.cpp:67: error: expected ‘;’ before ‘al’
1.find_position_bam.cpp:68: error: ‘reader’ was not declared in this scope
1.find_position_bam.cpp:68: error: ‘al’ was not declared in this scope
1.find_position_bam.cpp:73: error: ‘references’ was not declared in this scope
1.find_position_bam.cpp:76: error: ‘cout’ was not declared in this scope
1.find_position_bam.cpp:76: error: ‘endl’ was not declared in this scope
1.find_position_bam.cpp:105: error: ‘vector’ was not declared in this scope
1.find_position_bam.cpp:105: error: ‘CigarOp’ was not declared in this scope
1.find_position_bam.cpp:105: error: ‘cigars’ was not declared in this scope
1.find_position_bam.cpp:127: error: ‘reader’ was not declared in this scope

**Comment by pjb7687** [comment]
Hi @Aileensibs,

Would you please post the error to https://github.com/ibscge/digenome-toolkit2 ?
This repository is no longer maintained.

Best,
Jeongbin

**Comment by SeqCrafter** [comment]
> When I install this toolkit on my machine, error occurred with the bamtools, but I found the reported missing files by the error message are actually in the directory, so I can't figure out what's the problem here, could you please help me out?
> 
> Here is the error message:
> 
> 1.find_position_bam.cpp:7:27: error: api/BamReader.h: No such file or directory
> 1.find_position_bam.cpp:10: error: ‘BamTools’ is not a namespace-name
> 1.find_position_bam.cpp:10: error: expected namespace-name before ‘;’ token
> 1.find_position_bam.cpp: In function ‘void usage()’:
> 1.find_position_bam.cpp:13: error: ‘cout’ was not declared in this scope
> 1.find_position_bam.cpp:13: error: ‘endl’ was not declared in this scope
> 1.find_position_bam.cpp:15: error: ‘exit’ was not declared in this scope
> 1.find_position_bam.cpp: In function ‘int main(int, char**)’:
> 1.find_position_bam.cpp:42: error: ‘BamReader’ was not declared in this scope
> 1.find_position_bam.cpp:42: error: expected ‘;’ before ‘reader’
> 1.find_position_bam.cpp:50: error: ‘reader’ was not declared in this scope
> 1.find_position_bam.cpp:53: error: expected type-specifier before ‘exception’
> 1.find_position_bam.cpp:53: error: expected ‘)’ before ‘&’ token
> 1.find_position_bam.cpp:53: error: expected ‘{’ before ‘&’ token
> 1.find_position_bam.cpp:53: error: ‘e’ was not declared in this scope
> 1.find_position_bam.cpp:53: error: expected ‘;’ before ‘)’ token
> 1.find_position_bam.cpp:62: error: ‘reader’ was not declared in this scope
> 1.find_position_bam.cpp:64: error: ‘SamHeader’ does not name a type
> 1.find_position_bam.cpp:65: error: ‘RefVector’ does not name a type
> 1.find_position_bam.cpp:67: error: ‘BamAlignment’ was not declared in this scope
> 1.find_position_bam.cpp:67: error: expected ‘;’ before ‘al’
> 1.find_position_bam.cpp:68: error: ‘reader’ was not declared in this scope
> 1.find_position_bam.cpp:68: error: ‘al’ was not declared in this scope
> 1.find_position_bam.cpp:73: error: ‘references’ was not declared in this scope
> 1.find_position_bam.cpp:76: error: ‘cout’ was not declared in this scope
> 1.find_position_bam.cpp:76: error: ‘endl’ was not declared in this scope
> 1.find_position_bam.cpp:105: error: ‘vector’ was not declared in this scope
> 1.find_position_bam.cpp:105: error: ‘CigarOp’ was not declared in this scope
> 1.find_position_bam.cpp:105: error: ‘cigars’ was not declared in this scope
> 1.find_position_bam.cpp:127: error: ‘reader’ was not declared in this scope

Hello, I have the same problem, I can't compile and install the program, also, the problem in digenome-toolkit2 is still there, and I can't submit the problem, please, have you solved it?

**Comment by bitsyamagu** [comment]
This program  requires functions included in libbamtools.a.

At first, prepare libamtools.a of bamtools.

 git clone https://github.com/pezmaster31/bamtools.git

 cd bamtools

 mkdir build

 cd build

 cmake ..

We could build this by command like:
g++ -o 1.find_position_bam  1.find_position_bam.cpp -I${BAMTOOLS}/build/src -I${BAMTOOLS}/src -L${BAMTOOLS}/build/src  -lbamtools -lz

The ${BAMTOOLS} directory is the direcotry obtained by git clone.
